name: Build Whitepaper PDFs

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/Whitepaper_EN.md'
      - 'docs/Whitepaper_RU.md'

jobs:
  build-pdfs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex fonts-dejavu

      - name: Generate EN PDF
        run: |
          pandoc docs/Whitepaper_EN.md -o docs/Whitepaper_EN.pdf --pdf-engine=xelatex -V mainfont="DejaVu Serif"

      - name: Generate RU PDF
        run: |
          pandoc docs/Whitepaper_RU.md -o docs/Whitepaper_RU.pdf --pdf-engine=xelatex -V mainfont="DejaVu Serif"

      - name: Commit and push generated PDFs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-generate Whitepaper PDFs"
          file_pattern: docs/*.pdf
        env:
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_AUTOBOT }}
