name: 🪐 Daily History Generator

on:
  schedule:
    - cron: '0 4 * * *'   # каждый день в 04:00 UTC
  workflow_dispatch:       # ручной запуск

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run generator
        run: python3 utils/generate-history_index.py

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs/history/*.md docs/history_index.md
          git commit -m "🗓️ Авто-генерация истории за $(date +'%Y-%m-%d')" || echo "Nothing to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_AUTOBOT }}
