name: Update DevLog

on:
  push:
    paths:
      - 'docs/devlog/*.md'

jobs:
  update-devlog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Append latest commit to DevLog
        run: |
          DATE=2025-07-19
          COMMIT_MSG=Docs: Add initial ROADMAP.md with current milestones
          echo "- [] " >> docs/devlog/$(date "+%Y-%m").md

      - name: Auto-commit DevLog update
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update DevLog from latest commit"
          file_pattern: docs/devlog/*.md
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_AUTOBOT }}
